# Site settings

url: "https://diogogallo.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

# google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

# Forces https everywhere in your website, except when you serve it locally

force-https: False

#############
# HTML Head #
#############

author: "Diogo Gallo"
lang: "en"
title: "Diogo Gallo"
favicon: "/img/ico-codeview.ico"
description: "Diogo Gallo's personal website and blog. Including my Resume/CV and blogging mainly for software architecture and development world, personal takes, sharing of interest"
keywords: "diogogallo, blog, developer, toronto, canada, resume, java, cloud"

################
# Intro layout #
################

black-favicon: "/img/ico-codeview_big.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/avatar.jpeg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: False
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default  
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "<strong>passionate</strong> software architect<br><br>photography <strong>enthusiastic</strong><br><br><strong>super-hero</strong> daddy<br><br>creating <strong>amazing</strong> computer applications"

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "diogogallo"

###############
# Life Events #
###############

events:
  - image: "/img/career/synchro.jpg"
    date: "Since 2006"
    description: "Sr. Software Engineer @ Synchro"
  - image: "/img/career/ibta.png"
    date: "Apr 2005 - Apr 2006"
    description: "Postgraduated in Software Engineering - SOA and Component based @ IBTA"
  - image: "/img/career/IBOPE-logo.png"
    date: "Mar 2003 - Feb 2006"
    description: "Jr. Software Engineer @ IBOPE"
  - image: "/img/career/logo_ipt.gif"
    date: "Feb 2002 - Feb 2003"
    description: "Intern @ Instituto de Pesquisas Tecnológicas"
  - image: "/img/career/ufscar.png"
    date: "Jan 1999 - Dec 2002"
    description: "Bachelor's Degree in Computer Science @ Universidade Federal de São Carlos"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "diogogallo@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/diogogallo"
  - title: "twitter"
    url: "https://twitter.com/diogogallo"
  - title: "github"
    url: "https://github.com/diogogallo"
  - title: "instagram"
    url: "https://instagram.com/diogogallo"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/404.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Skills: 'skills'
  Experience: 'experience'
  Blog: 'blog'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

