# Site settings

url: "https://diogogallo.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

# google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

# Forces https everywhere in your website, except when you serve it locally

force-https: False

#############
# HTML Head #
#############

author: "Diogo Gallo"
lang: "en"
title: "Diogo Gallo"
favicon: "/img/ico-codeview.ico"
description: "Diogo Gallo's personal website and blog. Including my Resume/CV and blogging mainly for software architecture and development world, personal takes, sharing of interest"
keywords: "diogogallo, blog, developer, toronto, canada, resume, java, cloud"

################
# Intro layout #
################

black-favicon: "/img/ico-codeview_big.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/avatar.jpeg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: False
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default  
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "<strong>passionate</strong> software architect<br><br>photography <strong>enthusiastic</strong><br><br><strong>super-hero</strong> daddy<br><br>creating <strong>amazing</strong> computer applications"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
disqus-shortname: "diogogallo"

###############
# Life Events #
###############

events:
  - image: "/img/career/synchro.png"
    date: "Since 2012 | Software Architect @ <a href=\"http://www.synchro.com.br/en/" target=\"_blank\">Synchro</a>"
    description: "Currently acting as a Software Architect and Team Leader, moving solutions to Cloud environment using Microservices Architecture and responsible for the architecture and development of applications for the tax area, especially with electronic invoices and others electronic documents that have integration with government, serving major companies worldwide."
  - image: "/img/career/synchro.png"
    date: "2006 - 2012 | Sr. Software Engineer @ <a href=\"http://www.synchro.com.br/en/" target=\"_blank\">Synchro</a>"
    description: "Responsible for the development of applications for the tax area, especially with electronic invoices (NF-e) and others electronic documents that have integration with government, serving major companies worldwide."
  - image: "/img/career/ibta.png"
    date: "2005 - 2006 | Postgraduated @ <a href=\"http://www.ibta.edu.br/" target=\"_blank\">IBTA</a>"
    description: "Software Engineering - SOA and Component based"
  - image: "/img/career/ibope.png"
    date: "2003 - 2006 | Jr. Software Engineer @ <a href=\"http://www.ibope.com" target=\"_blank\">IBOPE</a>"
    description: "Worked in the development and maintenance of various projects, using Delphi and Java languages ​​and Microsoft SQL Server databases, exercising many different roles of software development, from requirements analysis to testing and deployment. Responsible for automation of all processes in Statistics Area, such as software for generation of samples for surveys and data tabulation."
  - image: "/img/career/ipt.png"
    date: "2002 - 2003 | Intern @ <a href=\"http://www.ipt.br/EN" target=\"_blank\">Instituto de Pesquisas Tecnológicas</a>"
    description: ""
  - image: "/img/career/ufscar.png"
    date: "1999 - 2002 | Degree in Computer Science @ <a href=\"http://www2.ufscar.br/english/index.php" target=\"_blank\">UFSCar</a>"
    description: "Bachelor's Degree in Computer Science at Universidade Federal de São Carlos"

# First image of the Career timeline
career-img: "/img/career/megadrive.jpg"

##################
# Contact layout #
##################

email: "diogogallo@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/diogogallo"
  - title: "twitter"
    url: "https://twitter.com/diogogallo"
  - title: "github"
    url: "https://github.com/diogogallo"
  - title: "instagram"
    url: "https://instagram.com/diogogallo"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/404.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Skills: 'skills'
  Experience: 'experience'
  Blog: 'blog'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

